# Generated by Django 3.0.8 on 2020-07-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do cliente', max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(help_text='Endereço de Email', max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
    ]
